### ISSUE TITLE
chickens become thirsty after getting carried

### ISSUE THREAD

**Issue by milibucket** [Tschipp/CarryOn#89] opened 2018-03-25 07:04 UTC
### Expected Behavior
I expected animals from animania to stay well fed after being carried

### Actual Behavior
when I carried a hen and a rooster, they become thirsty again after being put down

### Steps to Reproduce
Try carrying a well fed animania animal

### Version of Minecraft, Carry On, Forge
V1.8 of carry on on Minecraft 1.12.2

**Comment by Tschipp** [comment] 2018-03-25 08:47
Not able to reproduce. Is it a specific animal?

**Comment by milibucket** [comment] 2018-03-26 15:03
Maybe try carrying the Wyandotte hen or rooster while theyare well fed and watered. I didn't test it on other animals.

**Comment by Tschipp** [comment] 2018-03-28 13:36
You are right! But it is only a problem for chickens.

**Comment by capnkirok** [comment] 2018-04-06 17:39
Yup, bug in Animania... will be fixed in Animania 1.4.8. 1.12 version only.

**Comment by milibucket** [comment] 2018-04-07 00:14
Thank you !

**Closed** 2018-05-11 16:13 UTC
Labels: compat
