### ISSUE TITLE
Can not carry chests.

### ISSUE THREAD

**Issue by Nikos910** [Tschipp/CarryOn#299] opened 2021-03-16 22:00 UTC
I have tried changing keybinds still cannot move any chests.

**Comment by Tschipp** [comment] 2021-03-16 22:01
Please record a video of everything. Trying to pick up chests. Also show your keybinds.

**Comment by SrLink16** [comment] 2021-04-22 06:48
I have the same problem but in a server, the mod works in local

**Comment by NicolasPicavet** [comment] 2021-08-23 19:27
Try to come closer to the chest entity you want to pick up.

**Comment by starlingfire** [comment] 2022-01-27 15:33
I'm also experiencing this issue on 1.18, playing on modpack Medieval Minecraft v3 in single player.

Here's a video of me trying to pick up both vanilla and Quark chests, to no avail. I can pick up a horse though.
https://youtu.be/Sthazlp2_7s

Here are the tooltips for both chests:

**Vanilla chest**
minecraft:chest
#forge:chests
#forge:chests/wooden
#quark:boatable_chests
#snowyspirit:sled_container

**Quark oak chest**
quark:oak_chest
#forge:chests
#forge:chests/wooden
#quark:boatable_chests
#quark:revertable_chests
#snowyspirit:sled_container

Here is the NBT data for both items:
**Vanilla chest**
![vanilla](https://user-images.githubusercontent.com/26200565/151389803-00fdcb78-c13d-4f18-b89e-94f7e52fc14d.png)
**Quark chest**
![quark](https://user-images.githubusercontent.com/26200565/151389819-9b75e0fb-146d-4899-96c6-c207dc3f1dee.png)

I have also confirmed that all server-side whitelist and blacklist entries are removed.

**Comment by Tschipp** [comment] 2022-01-27 16:13
Ok, thanks for naming your keybinds. I'll try to recreate this.

**Comment by starlingfire** [comment] 2022-02-10 14:54
My issue is resolved with a compat commit to the TreeChop mod: https://github.com/hammertater/treechop/commit/3b9c91dd4f4a3c85be6265db037d83751ec69b04, as noted in issue https://github.com/hammertater/treechop/issues/105.

**Comment by Tschipp** [comment] 2022-02-11 08:44
> My issue is resolved with a compat commit to the TreeChop mod: [hammertater/treechop@3b9c91d](https://github.com/hammertater/treechop/commit/3b9c91dd4f4a3c85be6265db037d83751ec69b04), as noted in issue [hammertater/treechop#105](https://github.com/hammertater/treechop/issues/105).

So wait, I'm not quite sure what's happening here. When does that event fire? And does that mean the issue is on carryon's side or your side?

**Comment by hammertater** [comment] 2022-02-15 20:54
Hi @Tschipp, sorry for the trouble. I got sloppy when updating TreeChop to 1.18 and broke the CarryOn compatibility. starlingfire's issue is totally on my side and will be fixed shortly.

Note that the TreeChop conflict was introduced in January 2022, so it's unrelated to the original issue mentioned by Nikos910 and others.

Edit: it's fixed now. starlingfire's issue was the same as #366

**Comment by Tschipp** [comment] 2022-02-16 08:24
I see, thanks for clarifying!

**Closed as completed by Tschipp** 2022-02-16 08:24 UTC
