### ISSUE TITLE
cant place dupe bug

### ISSUE THREAD

**Issue by mortinho** [Tschipp/CarryOn#50] opened 2017-11-07 03:11 UTC
[powered thingies](https://minecraft.curseforge.com/projects/powered-thingies) has a crop cloner that renders the growing seed inside it. picking it up while theres a renderized plant leaves said render and only picks the block.
placing it back down anywhere other than the original place gives the cant place error and leaves a ghost crop cloner block. then if i pick and place the ghost back in the same place it was it makes a copy of the original block.
also doing that with the machine running crashed the server( im still asking for the log)

this is on:
minecraft 1.12.2
forge 14.23.0.2517
carry on 1.6.1
tesla powered thingies 1.0.10

[latest.log](https://github.com/Tschipp/CarryOn/files/1448550/latest.log)

**Comment by faceofcat** [comment] 2017-11-07 06:14
if you use the 'tesla wrench' from 'tesla core lib' on the crop cloner to pick it up and then place somewhere else it works fine... so the tile entity itself seems to not care much about placement in world (that was my first guess)

judging by the error I see in my dev workspace when adding 'carry on' it seems like this either doesn't copy all the blockstate properties, metadata, tile entity NBT from one place to another... or sets them in the wrong order... or I am expecting them in the wrong order and this mod gets it right... :)

but that's just a wild guess from a 5 minutes test run...

and btw... awesome mod!... I like it...

**Comment by Tschipp** [comment] 2017-11-07 13:13
Thanks for getting in touch! 
Carry On places first sets the appropriate BlockState and then calls World#getTileEntity to check if the block contains a TE. If it does, it then fetches the TE and reads the NBT that's stored on the carry-item. 
This could be two things: The Blockstate is not stored correctly (could happen if you're using IExtendedBlockstates) or you're overriding the readFromNBT function in the TE and that causes some error.

**Comment by Tschipp** [comment] 2017-12-12 14:19
@faceofcat Were you able to pinpoint the error? Or is it on my end?

**Comment by faceofcat** [comment] 2017-12-12 14:30
oh... I totally forgot about this... :(... kind of buried down under lots of other projects...

I think the problem was something around the moment in time when readFromNBT is read on my tile entity... but can't really remember the exact problem.

I'll make a mental note to look into this soon-ish :)

if no other mod complained about similar problems I guess it's safe to assume the problem is on my side.

**Comment by Tschipp** [comment] 2018-03-23 16:03
Closing this, as it doesn't seem to still be a problem

**Closed by Tschipp** 2018-03-23 16:03 UTC
Labels: question
