### ISSUE TITLE
Armor shoulders move while carry entities instead of keeping quiet

### ISSUE THREAD

**Issue by Meskino** [Tschipp/CarryOn#303] opened 2021-03-28 04:25 UTC
the armor shoulders move while carry entities, I don't know if it will be part of the vanilla code. but it would be great if they kept the arm posture somehow.

video demonstration:

https://user-images.githubusercontent.com/33664951/112742380-7d806480-8f64-11eb-975f-4497dbd38f34.mp4

**Comment by Tschipp** [comment] 2021-03-28 08:44
Duplicate of #1. Can't be fixed in vanilla without major hacks, but when obfuscate is installed it fixes this issue.

**Closed as completed by Tschipp** 2021-03-28 08:44 UTC
