### ISSUE TITLE
Picking up Desh Cable in Ad Astra made the player unable to interact with anything

### ISSUE THREAD

**Issue by UndisclosedBen** [Tschipp/CarryOn#472] opened 2023-03-02 04:18 UTC
### Expected Behavior
Be able to place picked up desh cable(from mod Ad Astra) back onto the ground

### Actual Behavior
Inability to place desh cable, upon death the desh cable remains being held.  The player was unable to interact with any blocks like breaking, opening chests, crafting tables, furnaces.  Whenever they tried to interact with anything the server output the error code in the attached text document.
[error.txt](https://github.com/Tschipp/CarryOn/files/10867465/error.txt)
The only fix that I found was to reset that player's data and for convenience I blacklisted all of Ad Astra's items.

### Steps to Reproduce
Connect Ad Astra solar panel and oxygen distributor with a desh cable, then pick up the desh cable.  This then did not allow the player to interact with anything else.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft - 1.19.2
Forge - 43.1.52
Carry On - 2.0.5.10
Ad Astra - 1.12.3

**Comment by Cape-City** [comment] 2023-03-07 19:00
We have not exact the same Behavior, we also can't place the picked desh cable back onto ground, but if the player dies, he can't respawn into the world (endless loop within the death screen). We set the gamerule doImmediateRespawn to true and the player spawns like a ghost and can't move. He also was invisible for other players.

Closing the game, deactivating the Carry On Mod and starting the game again fixed the issue temporarily. The user respawns normally and the hold item is gone. Closing the game, reactivating the Carry On Mod and the game seams to works fine again.

I think blacklisting all Ad Astra items will the best option so far.

MC 1.19.3
Fabric 0.14.17
Carry On - 2.0.4.15
Ad Astra - 1.13.4

**Comment by Tschipp** [comment] 2023-04-23 21:34
yeah maybe it should be on the default blacklist. FYI, in such cases, running /carryon clear should fix the issue.

**Comment by Tschipp** [comment] 2023-04-24 07:46
I've just tested this on forge 1.19.2, and it seems to work fine for me... I've connected a solar panel with the oxygen distributor and was able to pick up and place all cables. Worth noting that I was on the overworld

**Comment by Tschipp** [comment] 2023-07-04 17:49
I am closing this since I cannot reproduce it

**Closed as completed by Tschipp** 2023-07-04 17:49 UTC
Labels: follow up needed, 1.19
