### ISSUE TITLE
Sound glitch when carrying tamed wolf with Armor

### ISSUE THREAD

**Issue by vpontin** [Tschipp/CarryOn#106] opened 2018-05-15 23:02 UTC
### Issue
When carrying an armored wolf (from @CenturionFox 's [Wolf Armor and Storage](https://github.com/CenturionFox/wolfarmor)) the weird sound glitch happens. Maybe this is related to @OreCruncher [DynamicSurrondings](https://github.com/OreCruncher/DynamicSurroundings) because it adds footsteps sounds, i dont know.

### Steps to Reproduce
- Install CarryOn, [DynamicSurrondings](https://minecraft.curseforge.com/projects/dynamic-surroundings) and [Wolf Armor and Storage](https://minecraft.curseforge.com/projects/wolf-armor-and-storage)
- Tame a wolf and give it a armor
- Try to carry it (pref in Survival mode)

### Version of Minecraft, Carry On, Forge
- MC 1.12.2
- Forge 2691
- CarryOn 1.9
- Wolf Armor 2.1.0.24-RELEASE
- DynamicSurrondings 3.4.9.13

### Screenshots encouraged
- [Unlisted Youtube Video](https://www.youtube.com/watch?v=xSYfGci_oqI&feature=youtu.be)

**Comment by OreCruncher** [comment] 2018-05-17 14:57
Checked on the Dynamic Surroundings side of things and I didn't notice anything unusual with DS behavior.  The sound that is repeatedly playing is the Minecraft iron armor equip sound event.

**Comment by Tschipp** [comment] 2018-05-17 15:58
Very strange. Carry On is supposed to play the living sound of the animal on pickup, but just once.

**Comment by vpontin** [comment] 2018-05-17 21:14
Perharps this is something aggravated by @CenturionFox mod, but since he's offline i'm afraid this cant be fixed

**Comment by OreCruncher** [comment] 2018-05-18 14:38
More followup.  I checked into the issue some more as it relates to Dynamic Surroundings.  The sound play request that is happening is coming from the server, and since DS generates sound requests client side it's not me.  I did not dig into the server side - I just did enough work to confirm it's not Dynamic Surroundings. ;)

**Comment by CenturionFox** [comment] 2018-05-18 17:00
Yeah this is probably my bad.  I'm not sure how CarryOn works, but I think the issue is originating from Wolf Armor raising sound events during deserializeNBT on the capability, which... really doesn't need to happen.

**Comment by vpontin** [comment] 2018-05-18 23:10
Thanks Centurion!

**Comment by Tschipp** [comment] 2018-05-31 07:55
Great, thank you!

**Closed by Tschipp** 2018-05-31 07:55 UTC
Labels: Other Mod
