### ISSUE TITLE
Some mods Armor not fit Arm with Carry On mod

### ISSUE THREAD

**Issue by ColaLiao** [Tschipp/CarryOn#183] opened 2019-07-30 07:50 UTC
Ice and Fire mod 's some armor still not fit arm,
and Electroblob's Wizardry mod 's too.

### Version of Minecraft, Carry On, Forge

1.12.2

**Comment by Tschipp** [comment] 2019-07-30 07:52
Duplicate on #1, this is a known issue and will probably not be fixed in 1.12. If you want to fix this, install either LLibrary or Obfuscate.

**Comment by ColaLiao** [comment] 2019-07-30 14:30
But i install both LLibrary and Obfuscate already...

**Comment by Tschipp** [comment] 2019-07-31 21:03
An image would be useful...

**Comment by ColaLiao** [comment] 2019-08-06 07:24
**Electroblob's Wizardry Mod**
![Armor_ele](https://user-images.githubusercontent.com/16384174/62519339-ee3daf00-b85d-11e9-91bb-53307f72d4e7.png)

**Ice and Fire Mod**
![Ice_01](https://user-images.githubusercontent.com/16384174/62519434-1e854d80-b85e-11e9-9354-c290b352de78.png)
![Ice_02](https://user-images.githubusercontent.com/16384174/62519450-2644f200-b85e-11e9-9682-ae88622faa02.png)
![Ice_03](https://user-images.githubusercontent.com/16384174/62519455-28a74c00-b85e-11e9-8659-f5cf48d14104.png)

**ChinJuFu Mod**
![chinjufu_01](https://user-images.githubusercontent.com/16384174/62519480-3d83df80-b85e-11e9-804e-5ee5d9c59f9b.png)
![chinjufu_02](https://user-images.githubusercontent.com/16384174/62519489-42e12a00-b85e-11e9-8498-43af5fb69cb1.png)

**Comment by Tschipp** [comment] 2019-10-30 15:15
Can't really do much... going to close this as a duplicate of #1

**Closed as completed by Tschipp** 2019-10-30 15:15 UTC
Labels: duplicate
