### ISSUE TITLE
Launch crash with v2.0.4.6

### ISSUE THREAD

**Issue by merfed** [Tschipp/CarryOn#458] opened 2023-01-30 16:36 UTC
### Expected Behavior
Launch.

### Actual Behavior
Crashes.

### Steps to Reproduce
Launch with Carry On and Macaw's Trap Doors

### Version of Minecraft, Carry On, Forge/Fabric

forge 43.2.3

mcw-trapdoors-1.0.8-mc1.19.2forge
carryon-forge-1.19.2-2.0.4.6

### Screenshots encouraged

```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.module.ResolutionException: Modules carryon and MixinExtras export package com.llamalad7.mixinextras to module mcwtrpdoors
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.
```

---

This looks to be similar to the Artifacts crash, and another crash posted in #455 by Damdrara. So I doubt this is isolated to _just_ Macaw's Trapdoors, and will probably hit a lot of other mods also.

**Comment by Tschipp** [comment] 2023-01-31 09:54
Do you have any other mods? I can't reproduce this with just carry on and Macaw's trapdoors.

**Comment by merfed** [comment] 2023-01-31 16:54
Yeah, I'll put a list below. So I got more time to look into this. Mostly by disabling the mod spitting out this error:

```
java.lang.module.ResolutionException: Modules carryon and MixinExtras export package com.llamalad7.mixinextras to module mcwtrpdoors
```

And keeping Carry On enabled, and then loading each mod that subsequently replaced `mcwtrpdoors` as I loaded the instance. The following list is what I got before I decided to take a break:

- Artifacts
- Ad Astra
- Entangled
- Friends and Foes
- Thermal Systeams
- Apotheosis
- JAMD
- Iron Chests
- Pigpen
- Modonomicon
- Integrated Tunnels
- Mekanism Additions
- Cooking for Blockheads
- Night Lights
- Mekanism Tools
- Spectrelib

Also when all mods are enabled per the list below (only a few are turned off by default), the start up error affected module will typically be random based on whats installed. Going to assume the load order isn't set in stone for mods, and maybe one's getting there first?

In that case I saw these mods as affected:

- Entity Collision FPS Fix
- Cooking For Blockheads
- AE2 Things
- Additional Lanterns
- Fancy Menu
- Industrial Foregoing


```
  [✔] accelerated-decay-forge-1.0.0+mc1.19.2
  [✔] ad_astra-forge-1.19.2-1.12.1
  [✔] additional_lights-1.19-2.1.5
  [✔] additionallanterns-1.0.3-forge-mc1.19
  [✔] Adorn-3.8.1+1.19.2-forge
  [✔] AdvancedPeripherals-0.7.22b
  [✔] AE2-Things-1.1.1
  [✔] AE2WTLib-12.8.4
  [✔] AEAdditions-1.19.2-4.0.2
  [✔] AEInfinityBooster-1.19.2-1.2.0+11
  [✔] AllTheCompressed-1.19.2-2.0.0
  [✔] allthemodium-2.1.5-1.19.2-43.1.1
  [✔] alltheores-2.0.2-1.19.2-43.1.3
  [✔] almostunified-forge-1.19.2-0.3.3
  [✔] alternate-current-mc1.19-1.4.0
  [✔] AmbientSounds_FORGE_v5.2.13_mc1.19.2
  [✔] Amplified_Nether_v1.2
  [✔] Apotheosis-1.19.2-6.0.3
  [✔] appleskin-forge-mc1.19-2.4.2
  [✔] appliedcooking-2.0.3
  [✔] appliedenergistics2-forge-12.9.2
  [✔] Applied-Mekanistics-1.3.3
  [✔] Aquaculture-1.19.2-2.4.8
  [✔] architectury-6.3.56-forge
  [✔] ars_creo-1.19.2-3.1.3
  [✔] ars_instrumentum-1.19.2-3.2.2
  [✔] ars_nouveau-1.19.2-3.8.4
  [✔] artifacts-1.19.2-5.0.1
  [✔] AutoRegLib-1.8.2-55
  [✔] badpackets-forge-0.2.1
  [✔] balm-4.5.3
  [✔] BasicNetherOres-1.19.2-8.2.0
  [✔] BetterAdvancements-1.19.2-0.3.0.148
  [✔] BetterCompatibilityChecker-1.0.9-build.38+mc1.19.2
  [✔] BetterF3-4.0.0-Forge-1.19.2
  [✔] bettermounthud-1.2.0
  [✔] BetterPingDisplay-1.19-1.1
  [✔] betterstats-2.2+1.19.2
  [✘] blockui-1.19-0.0.64-ALPHA.jar (disabled)
  [✔] blue_skies-1.19.2-1.3.20
  [✔] Bookshelf-Forge-1.19.2-16.2.17
  [✔] Botania-1.19.2-436-FORGE
  [✔] BotanyPots-Forge-1.19.2-9.0.24
  [✔] BotanyTrees-Forge-1.19.2-5.0.4
  [✔] botarium-forge-1.19.2-1.8.2
  [✔] buildersaddition-1.19.2-20220926a
  [✔] BuildGuide-1.19.2-0.3.3
  [✔] buildinggadgets-3.16.1-build.15+mc1.19.2
  [✔] bwncr-forge-1.19.2-3.14.1
  [✔] canary-mc1.19.2-0.1.8
  [✔] carryon-forge-1.19.2-2.0.4.6
  [✔] cc-tweaked-1.19.2-1.101.1
  [✔] Chimes-1.1.4-1.19
  [✘] chisels-and-bits-forge-1.3.126.jar (disabled)
  [✔] cloth-config-8.2.88-forge
  [✔] Clumps-forge-1.19.2-9.0.0+14
  [✔] CodeChickenLib-1.19.2-4.3.0.470-universal
  [✔] cofh_core-1.19.2-10.0.0.29
  [✔] comforts-forge-6.0.3+1.19.2
  [✔] CommonCapabilities-1.19.2-2.8.3
  [✔] compactmachines-5.1.0
  [✔] configured-2.0.1-1.19.2
  [✔] connectedglass-1.1.6-forge-mc1.19
  [✔] connectivity-1.19.2-3.4
  [✔] constructionwand-1.19.1-2.8
  [✔] Controlling-forge-1.19.2-10.0+7
  [✔] cookingforblockheads-forge-1.19.2-13.3.0
  [✔] CosmeticArmorReworked-1.19.2-v1a
  [✔] create_crystal_clear-0.1.2e-1.19.2
  [✔] create_enchantment_industry-1.19.2-for-create-0.5.0.h-1.1.12
  [✔] create-1.19.2-0.5.0.i
  [✔] createaddition-1.19.2-20221230a
  [✔] create-confectionery1.19.2_v1.0.8
  [✔] createplus-1.19.2_v0.5.2a
  [✔] CreativeCore_FORGE_v2.9.3_mc1.19.2
  [✔] creativedisk-1.0.0+mc1.19.2
  [✔] creeperoverhaul-2.0.6-forge
  [✔] crittersandcompanions-1.19.2-1.1.2
  [✔] Cucumber-1.19.2-6.0.3
  [✔] curios-forge-1.19.2-5.1.1.0
  [✔] Cyclic-1.19.2-1.7.14
  [✔] CyclopsCore-1.19.2-1.17.4
  [✔] DarkUtilities-Forge-1.19.2-13.1.7
  [✔] debugify_reforged-1.0.0-forge-1.19.2
  [✔] Decorative+Blocks-forge-1.19.2-3.0.0
  [✔] deeperdarker-forge-1.1.6-forge
  [✔] deepresonance-1.19-4.1.0
  [✔] Delightful-1.19-3.1.4
  [✔] DeLogger-4.7.0-build.9+mc1.19.2
  [✔] DistantHorizons-1.6.9a-1.19.2
  [✔] domum_ornamentum-1.19-1.0.75-ALPHA-universal
  [✔] DungeonsArise-1.19.2-2.1.54-release
  [✔] durabilityviewer-1.19.1-forge42.0.1-1.10
  [✔] dynamiclightsreforged-1.19.2_v1.4.0
  [✔] EasyAnvils-v4.0.6-1.19.2-Forge
  [✔] eccentrictome-1.19.2-1.9.1
  [✔] EdivadLib-1.19.2-1.2.0
  [✔] elevatorid-1.19.2-1.8.9
  [✔] EnchantmentRequirements-1.19.2-1.2.0
  [✔] enderchests-1.19-1.10.1
  [✔] EnderStorage-1.19.2-2.10.1.181-universal
  [✔] endertanks-1.19-1.12.1
  [✔] entangled-1.3.12-forge-mc1.19
  [✔] entangledfix-1.0
  [✔] Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0
  [✔] entityculling-forge-1.5.2-mc1.19.1
  [✔] everycomp-1.19.2-2.2.3
  [✔] EvilCraft-1.19.2-1.2.14
  [✔] ExperienceBugFix-1.19-1.41.2.2
  [✔] experienceobelisk-v1.3.8-1.19.2
  [✔] explorify-forge-1.19-1.3.0
  [✔] ExtraStorage-1.19.2-3.0.1
  [✔] ExtremeReactors2-1.19.2-2.0.55
  [✔] extremesoundmuffler-3.35-forge-1.19.2
  [✔] Fallingleaves-1.19.1-1.3.1
  [✔] fancymenu_forge_2.12.9_MC_1.19-1.19.2
  [✔] FarmersDelight-1.19-1.2.0
  [✔] FarmersRespite-1.19-2.0
  [✔] farsight-1.19.2-2.1
  [✔] FastFurnace-1.19.2-7.0.0
  [✔] Fastload-Reforged-2.6.9+1.19.2
  [✔] FastSuite-1.19.2-4.0.0
  [✔] FastWorkbench-1.19.2-7.0.1
  [✔] ferritecore-5.0.3-forge
  [✔] flatbedrock-forge-2.0.0-build.14+mc1.19.2
  [✔] FluxNetworks-1.19.2-7.1.3.12
  [✔] flywheel-forge-1.19.2-0.6.8.a
  [✔] FramedBlocks-6.7.0
  [✔] FriendlyFire-Forge-1.19.2-14.0.1
  [✔] friendsandfoes-forge-mc1.19.2-1.6.8
  [✔] ftbbackups2-forge-1.19.2-1.0.17
  [✔] ftb-chunks-forge-1902.3.14-build.218
  [✔] ftb-essentials-1902.1.10-build.47
  [✔] ftb-library-forge-1902.3.11-build.166
  [✔] ftb-teams-forge-1902.2.12-build.95
  [✔] functionalstorage-1.19.2-1.1.3
  [✔] Galosphere-1.19.2-1.2.0-Forge
  [✔] geckolib-forge-1.19-3.1.39
  [✔] geophilic-forge-1.19-1.0.1
  [✔] glassential-forge-1.19-1.2.4
  [✔] Gobber_Delight_1.1.1_Forge_1.19.2
  [✔] Gobber2-Forge-1.19.2-2.7.28
  [✔] goblintraders-1.8.0-1.19.2
  [✔] HealthOverlay-1.19.2-7.2.1
  [✔] HostileNeuralNetworks-1.19.2-4.0.2
  [✔] IC2Classic-1.19.2-2.0.3
  [✔] ImmersiveEngineering-1.19.2-9.0.0-153
  [✔] immersive-portals-2.3.1-mc1.19.2-forge
  [✔] industrial-foregoing-1.19.2-3.3.2.1-3
  [✔] IntegratedCrafting-1.19.2-1.0.26
  [✔] IntegratedDynamics-1.19.2-1.14.7
  [✔] IntegratedTerminals-1.19.2-1.4.1
  [✔] IntegratedTunnels-1.19.2-1.8.17
  [✔] InventoryProfilesNext-forge-1.19-1.9.1
  [✔] ironchest-1.19.2-14.2.7
  [✔] itemcollectors-1.1.6-forge-mc1.19
  [✔] Jade-1.19.1-forge-8.7.0
  [✔] JadeAddons-1.19.2-forge-3.3.0
  [✔] jamd-forge-2.0.5-build.12+mc1.19.2
  [✔] JAOPCA-1.19.2-4.2.4.7
  [✔] javd-forge-4.0.1-build.2+mc1.19.2
  [✔] jmi-forge-1.19.2-0.13-30
  [✔] journeymap-1.19.2-5.9.2-forge
  [✔] jumpboat-1.19-0.1.0.5
  [✔] kleeslabs-forge-1.19-12.1.0
  [✔] konkrete_forge_1.6.0_MC_1.19-1.19.2
  [✔] kotlinforforge-3.9.1-all
  [✔] krypton-0.2.0
  [✔] kubejs-forge-1902.6.0-build.135
  [✘] laserio-1.5.2.jar (disabled)
  [✔] lazydfu-1.19-1.0.2
  [✔] libIPN-forge-1.19-2.0.2
  [✔] LibX-1.19.2-4.2.8
  [✔] light-overlay-7.0.1-forge
  [✔] littlecontraptions-forge-1.19.2.0
  [✔] littlelogistics-mc1.19.2-v1.3.1
  [✔] lootr-1.19-0.3.22.59
  [✔] luggage-1.19-1.5.3
  [✔] mahoutsukai-1.19.2-v1.34.38
  [✔] mcjtylib-1.19-7.1.1
  [✔] mcw-bridges-2.0.6-mc1.19.2forge
  [✔] mcw-doors-1.0.7-mc1.19.2
  [✔] mcw-fences-1.0.7-mc1.19.2forge
  [✔] mcw-furniture-3.0.2-mc1.19.2
  [✔] mcw-lights-1.0.5-mc1.19.2forge
  [✔] mcw-paths-1.0.2forge-mc1.19.2
  [✔] mcw-trapdoors-1.0.8-mc1.19.2forge
  [✔] mcw-windows-2.1.1-mc1.19.2forge
  [✔] megacells-forge-2.0.0-beta.7-1.19.2
  [✔] Mekanism-1.19.2-10.3.5.473
  [✔] MekanismAdditions-1.19.2-10.3.5.473
  [✔] MekanismGenerators-1.19.2-10.3.5.473
  [✔] MekanismTools-1.19.2-10.3.5.473
  [✔] merequester-1.19.2-1.0.3
  [✔] mob_grinding_utils-1.19.2-0.4.47
  [✘] modelfix-1.10.jar (disabled)
  [✔] modnametooltip-1.19-1.19.0
  [✔] modonomicon-1.19.2-1.23.2
  [✔] moonlight-1.19.2-2.2.2-forge
  [✔] MouseTweaks-forge-mc1.19-2.23
  [✔] MysticalAgradditions-1.19.2-6.0.2
  [✔] MysticalAgriculture-1.19.2-6.0.5
  [✔] MysticalCustomization-1.19.2-4.0.1
  [✔] naturalist-forge-2.1.1-1.19.2
  [✔] NaturesCompass-1.19.2-1.10.0-forge
  [✔] Neat-1.19-32
  [✔] netherportalfix-forge-1.19-10.0.0
  [✔] NethersDelight-1.19-3.0
  [✔] nightlights_1.19.2_1.1
  [✔] NoChatReports-FORGE-1.19.2-v1.5.1
  [✔] no-telemetry-1.6.0
  [✔] notenoughcrashes-4.2.1+1.19.2-forge
  [✔] occultism-1.19.2-1.67.0
  [✔] oculus-mc1.19.2-1.2.8a
  [✔] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13
  [✔] Patchouli-1.19.2-77
  [✔] PigPen-Forge-1.19.2-11.1.2
  [✔] pipez-1.19.2-1.0.1
  [✔] Placebo-1.19.2-7.1.2
  [✔] pluto-mc1.19.2-0.0.7
  [✔] pneumaticcraft-repressurized-1.19.2-4.2.0-16
  [✔] polylib-forge-1900.0.2-build.42
  [✔] polymorph-forge-0.46.1+1.19.2
  [✔] potionsmaster-0.6.0-1.19.2-43.1.1
  [✔] Powah-4.0.6
  [✔] PresenceFootsteps-1.19.2-1.6.4.1-forge
  [✔] productivebees-1.19.2-0.10.4.0
  [✔] PuzzlesLib-v4.3.12-1.19.2-Forge
  [✔] Quark-3.4-389
  [✘] radon-0.8.2.jar (disabled)
  [✔] rangedpumps-1.0.0
  [✔] Reblured-1.19.1-1.2.0
  [✔] rebornstorage-1.19.2-5.0.2
  [✔] rechiseled-1.0.12a-forge-mc1.19
  [✔] RedWireCore-1.19.2-1.3r
  [✔] RedWireLampsAndLighting-1.19.2-1.3r
  [✔] refinedstorage-1.11.1
  [✔] refinedstorageaddons-0.9.0
  [✔] REIPluginCompatibilities-forge-9.0.44
  [✔] reliquary-1.19.2-2.0.20.1166
  [✔] resourcefulconfig-forge-1.19.2-1.0.18
  [✔] resourcefullib-1.1.20
  [✔] rftoolsbase-1.19.1-4.1.1
  [✔] rftoolsbuilder-1.19.1-5.2.0
  [✔] rftoolscontrol-1.19-6.1.0
  [✔] rftoolsdim-1.19-9.1.0
  [✔] rftoolspower-1.19-5.1.1
  [✔] rftoolsstorage-1.19-4.1.0
  [✔] rftoolsutility-1.19-5.1.0
  [✔] rhino-forge-1902.2.2-build.264
  [✔] RoughlyEnoughItems-9.1.587
  [✔] RoughlyEnoughProfessions-forge-1.19.2-1.1.3
  [✔] rsrequestify-2.3.0
  [✔] rubidium_extras-1.19.2_v1.3.2
  [✔] rubidium-0.6.2
  [✔] Runelic-Forge-1.19.2-14.1.4
  [✔] saturn-mc1.19.2-0.0.1
  [✔] seasonhud-1.19.2-1.3.5
  [✔] sebastrnlib-2.0.1
  [✔] seeds-1.19.2-1.1.3
  [✔] sereneseasonfix-1.19.2-1.0.7
  [✔] SereneSeasons-1.19.2-8.1.0.24
  [✔] shetiphiancore-1.19-3.11.3
  [✔] shutupexperimentalsettings-1.0.5
  [✔] SilentCompat-forge-1.19.2-1.0.4
  [✔] silent-gear-1.19.2-3.2.3
  [✔] silent-lib-1.19.2-7.0.3
  [✔] simpletomb-1.19-1.0.15
  [✔] simplylight-1.19.2-1.4.5-build.42
  [✔] SkyVillages-1.0.1-1.19-forge-release
  [✔] sliceanddice-2.0.0
  [✔] SmartBrainLib-forge-1.19.2-1.8
  [✘] smoothboot(reloaded)-mc1.19.2-0.0.2.jar (disabled)
  [✔] smoothchunk-1.19.1-2.0
  [✔] sons-of-sins-1.19.2-1.1.1
  [✔] sophisticatedbackpacks-1.19.2-3.18.40.779
  [✔] sophisticatedcore-1.19.2-0.5.38.203
  [✔] sophisticatedstorage-1.19.2-0.6.16.276
  [✔] spiderstpo-1.19.2-2.0.4
  [✔] spirit-forge-1.19.2-2.2.3
  [✔] starbunclemania-1.19.2-1.0.5.2
  [✔] starlight-1.1.1+forge.cf5b10b
  [✔] Steam_Rails-1.19.2-1.0.6
  [✔] structure_gel-1.19.2-2.7.1
  [✘] structurize-1.19.2-1.0.467-BETA.jar (disabled)
  [✔] supermartijn642configlib-1.1.6b-forge-mc1.19
  [✔] supermartijn642corelib-1.1.1a-forge-mc1.19
  [✔] supplementaries-1.19.2-2.2.45
  [✔] systeams-1.1.1
  [✔] tempad-forge-1.19.2-1.4.3
  [✔] TerraBlender-forge-1.19.2-2.0.1.128
  [✔] Terralith_v2.3.5
  [✔] TextruesRubidiumOptions-1.0.4-mc1.19.2
  [✔] the_bumblezone_forge-6.6.3+1.19.2
  [✔] thermal_cultivation-1.19.2-10.0.0.15
  [✔] thermal_expansion-1.19.2-10.0.0.19
  [✔] thermal_foundation-1.19.2-10.0.0.38
  [✔] thermal_innovation-1.19.2-10.0.0.16
  [✔] thermal_integration-1.19.2-10.0.0.11
  [✔] thermal_locomotion-1.19.2-10.0.0.12
  [✔] ThermalExtra+1.19.2-3.0.1
  [✔] titanium-1.19.2-3.7.1-24
  [✔] ToolKit-2.3.6-build.10+mc1.19.1
  [✔] torchmaster-19.2.0
  [✔] TrampleStopper-3.8.1-build.35+mc1.19.2
  [✔] trashcans-1.0.16-forge-mc1.19
  [✔] TravelAnchors-1.19.2-4.1.2
  [✔] TravelersTitles-1.19.2-Forge-3.1.2
  [✔] twilightforest-1.19.2-4.2.1468-universal
  [✔] UnusualEnd1.19_V1.2.7
  [✔] VisualWorkbench-v4.2.1-1.19.2-Forge
  [✔] vitalize-forge-1.19.2-1.1.1
  [✔] waystones-forge-1.19-11.1.0
  [✔] whisperwoods-1.19-2.1.1-forge
  [✔] wirelesschargers-1.0.7-forge-mc1.19
  [✔] WitherSkeletonTweaks-1.19.2-8.0.0
  [✔] xnet-1.19-5.1.0
  [✔] XNetGases-1.19.1-4.0.0
  [✔] XyCraft+Core-0.5.17
  [✔] XyCraft+Override-0.5.17
  [✔] XyCraft+World-0.5.17
  [✔] YungsApi-1.19.2-Forge-3.8.2
  [✔] YungsBetterDesertTemples-1.19.2-Forge-2.2.1
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.0
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Forge-2.1.0
  [✔] YungsExtras-1.19.2-Forge-3.1.0
  [✔] ZeroCore2-1.19-2.1.26
```

**Comment by Tschipp** [comment] 2023-01-31 20:26
Thanks for the in depth analysis!

**Comment by MrsMoondog** [comment] 2023-01-31 20:26
Hello,
 We are also experiencing this crash on our server. We are running ATM8 with a few extras: Cyclic with it's dependency PuzzleLIb, plain grinder, and Enhanced Infusion.

I tried [carryon-forge-1.19.2-2.0.4.6], [carryon-forge-1.19.3-2.0.3.13], & [carryon-forge-1.19.2-2.0.3.4]. Server crashed with all three.

**Comment by Tschipp** [comment] 2023-02-01 20:20
Should be fixed now.

**Closed as completed by Tschipp** 2023-02-01 20:20 UTC
Labels: bug, 1.19
