### ISSUE TITLE
1.19.2 Crash on Startup

### ISSUE THREAD

**Issue by NathanRodz92** [Tschipp/CarryOn#452] opened 2023-01-20 05:00 UTC
### Expected Behavior
Crashes on startup

### Actual Behavior
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Caused by: java.lang.module.ResolutionException: Modules carryon and MixinExtras.rc5 export package com.llamalad7.mixinextras.injector.wrapoperation to module appleskin
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Version of Minecraft, Carry On, Forge 
Minecraft 1.19.2 
Carryon: 2.0.3.4
Forge 43.1.1

**Comment by Looodon** [comment] 2023-01-20 06:17
I have this too on:

Forge 43.2.3
Minecraft 1.19.2
Carryon 2.0.3.4

but im getting Exit Code: 1 and the logs are showing nothing helpful

**Comment by mpcarlos87** [comment] 2023-01-22 20:15
@NathanRodz92 @Looodon do you have "Artifacts" (https://www.curseforge.com/minecraft/mc-mods/artifacts) mod installed? I'm experiencing same error as Looodon having both installed (no other mods). If I uninstall one of them Minecraft runs perfect.
![20230122-Crash](https://user-images.githubusercontent.com/4833414/213938144-522aa1e6-ab9f-4851-abba-e6d4dad6b9a1.PNG)

Added an issue in Artifacts repository: https://github.com/ochotonida/artifacts/issues/187

**Comment by gchpaco** [comment] 2023-01-22 21:12
Yeah I have this problem and artifacts, but of the two CarryOn is the one that most recently updated, so I'm thinking it's *probably* something on this side.  Happily going back to the previous release fixes the issue, so it's something added between then and now.

**Comment by mpcarlos87** [comment] 2023-01-22 22:26
> Yeah I have this problem and artifacts, but of the two CarryOn is the one that most recently updated, so I'm thinking it's _probably_ something on this side. Happily going back to the previous release fixes the issue, so it's something added between then and now.

True, I was able to confirm. Thanks for your help!

artifacts-1.19.2-5.0.1.jar with carryon-forge-1.19.2-2.0.3.4.jar -> Crashes
artifacts-1.19.2-5.0.1.jar with carryon-forge-1.19.2-2.0.2.3.jar -> Works

**Comment by ChaseCarlson** [comment] 2023-01-22 22:49
I'm getting this same thing. Issues with dankstorage, sophisticatedcore, and probably more if I had kept deleting mods.

EDIT: I was able to fix by reverting to the prior mod release

**Comment by NathanRodz92** [comment] 2023-01-22 23:34
This is what I get following everyones idea with artifacts only loaded. I am using multiMC log to get this log. 

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Caused by: java.lang.module.ResolutionException: Module MixinExtras.rc5 contains package com.llamalad7.mixinextras.injector, module carryon exports package com.llamalad7.mixinextras.injector to MixinExtras.rc5
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:806)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more

**Comment by zachsai** [comment] 2023-01-23 04:52
Same issue here, hopefully a fix can come out for the latest patch

**Comment by Looodon** [comment] 2023-01-23 06:07
Forge 43.2.3
Minecraft 1.19.2
Carryon 2.0.3.4

My issue is happening without the artifacts mod, but i have 97 other mods so Idk if its because of carryon on its own or its combination with one of the other 97. What ik for sure is its happening in the latest version of carryon and not the previous

**Comment by ghost** [comment] 2023-01-24 23:10
Guys, just revert to an older version till the issue is fixed

**Comment by FooterManDev** [comment] 2023-01-26 15:33
I am also experiencing this issue, no crash log is written.

**Comment by Tschipp** [comment] 2023-01-26 16:59
I know the cause of this issue and am working on a fix

**Comment by Tschipp** [comment] 2023-01-27 19:50
Should be fixed with the latest version

**Closed as completed by Tschipp** 2023-01-27 19:50 UTC
Labels: bug, 1.19, forge
