### ISSUE TITLE
Enhanced Block Entities makes chests invisible when carried

### ISSUE THREAD

**Issue by angryos** [Tschipp/CarryOn#693] opened 2024-09-26 12:29 UTC
### Expected Behavior
The chest to be visible

### Actual Behavior
The chest is invisible

### Steps to Reproduce
carryon-fabric-1.20.1-2.1.2.7
fabric-0.92.2+1.20.1
enhancedblockentities-0.9+1,20

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1 fabric

**Comment by sigmaminecrafter** [comment] 2024-09-28 00:36
yep and it make the water go weird;

**Comment by sigmaminecrafter** [comment] 2024-09-28 00:37
Fix this PLEASE

**Comment by sigmaminecrafter** [comment] 2024-09-28 00:37
I CANT GET MORE FPS

**Comment by sigmaminecrafter** [comment] 2024-09-28 00:37
PLEASE PLEASE!

**Comment by sigmaminecrafter** [comment] 2024-09-28 03:09
yet the mod Carrier works fine 
chest is invisible in first person but visible in third - which is good enough

**Comment by sigmaminecrafter** [comment] 2024-09-29 22:22
why is this suddenly working again for me
 i switched back cause carrier mod cant pick up variant chests or most mobs
 and i have EBE
 chest invisible in first but visible in third ;;-;

**Comment by sigmaminecrafter** [comment] 2024-09-29 22:24
and water not glitched for me anymore
 before i pick up a chest and it was like i picked up all the water infront of me like it all would anchor itself to the chest and move at whatever angle i put the chest at
 only visually tho

**Comment by sigmaminecrafter** [comment] 2024-09-29 22:26
now if only the carry animation was compatible with that new animation mod Animation Overhaul

**Comment by sigmaminecrafter** [comment] 2024-09-29 22:44
wait the water glitch only happens with normal oak chests? with every other chest variant it works fine? so werird

**Comment by sigmaminecrafter** [comment] 2024-09-29 22:46
vanilla chests break it... (oak and trapped)  but i have variant barrels  and they all work fine

**Comment by sigmaminecrafter** [comment] 2024-09-29 22:55
using different chest variant mod (mcv) kinda helps cuz i can use oak chests again; but normal chests that spawn wil still be invisible and cause the water anchored to chest glitch if shaders are on
which is kinda bad for exploring shipwrecks when u have shaders on

**Comment by sigmaminecrafter** [comment] 2024-09-29 23:23
same 4 me but tbh removing EBE mod i cant even notice a performance difference and this mod works fine now after so

**Comment by sigmaminecrafter** [comment] 2024-09-29 23:25
i have so much mods and have stable 144 fps using reddit guide top comment https://www.reddit.com/r/fabricmc/comments/17fasim/what_are_the_best_optimization_mods_for_1201/ 
i think this mod mightve actually caused lag but idk

**Comment by sigmaminecrafter** [comment] 2024-09-29 23:31
exordium 
limited chunks
faster random
feytweaks
gpu tape
mods helped me a lot

**Comment by EnchantedBread** [comment] 2024-11-05 11:03
Minecraft 1.20.1 | Carry On 2.1.2.7 | Fabric Loader 0.16.9

I have the same issue; only the chest is invisible, everything else works, fine.

(also using enhanced block entities)

modlist: https://drive.google.com/file/d/1wA8b5_2_9BQDyqPMQ0vtZxRQ28SelGwU/view?usp=sharing

modpack: https://drive.usercontent.google.com/download?id=1RfPkt6sjFZ7fsaQZCNoe89B9pnUsskPt&export=download

**Comment by Tschipp** [comment] 2024-12-28 15:44
duplicate of #559

**Closed as completed by Tschipp** 2024-12-28 15:44 UTC
