### ISSUE TITLE
Can't place down entities

### ISSUE THREAD

**Issue by TheCreepyPirate** [Tschipp/CarryOn#565] opened 2023-10-10 17:22 UTC
Can't place down entities with CarryOn, was working just fine until the addition of other mods.

Steps to Reproduce
PIck up entity
Try to place it down
Can't

 Version of Minecraft, Carry On, Forge/Fabric

Minecraft 1.20.1
CarryOn 2.1.2.5
Forge 47.1.3
![imagem_2023-10-10_142133315](https://github.com/Tschipp/CarryOn/assets/86327756/f601fe3c-14c9-4979-ae1c-e14658b3ec60)

**Comment by Mikuo00** [comment] 2023-11-02 21:31
I encounter the same issue every time I pick up an entity. I become immediately stuck holding it, and the only way to get rid of it is by using the command /kill @s or /kill [username]. I've also observed that if you have 'keep inventory' enabled, you'll still be trapped in the glitch. So, you need to ensure that it's turned off when you execute the command. However, picking up spawners works just fine. The best way to identify the issue is to remove all of them except for the 'carry on' mod, then gradually add one mod at a time and test the game. Check if it works with each addition, and continue until you find the mod that causes the issue. Please note that I haven't tried this solution yet, so I can't confirm if it works. You can then try installing a different version of the mod or simply remove it altogether.

**Comment by TheCreepyPirate** [comment] 2023-11-04 01:18
> I encounter the same issue every time I pick up an entity. I become immediately stuck holding it, and the only way to get rid of it is by using the command /kill @s or /kill [username]. I've also observed that if you have 'keep inventory' enabled, you'll still be trapped in the glitch. So, you need to ensure that it's turned off when you execute the command. However, picking up spawners works just fine. The best way to identify the issue is to remove all of them except for the 'carry on' mod, then gradually add one mod at a time and test the game. Check if it works with each addition, and continue until you find the mod that causes the issue. Please note that I haven't tried this solution yet, so I can't confirm if it works. You can then try installing a different version of the mod or simply remove it altogether.

So, i found the issue, i forgot to close this thread but here we go, it was a conflict between "Rats" mod and Carry On, maybe because on Rats you're also able to pick up your rat, i can't think of anything logical about this but it must be something related

**Comment by onspeed8** [comment] 2023-11-06 12:58
For others who have this issue you can use the **/carryon place** command to place down the entity you have stuck in your hands.

**Comment by Kaiwawa** [comment] 2023-11-07 19:01
@TheCreepyPirate this is why it happens, they are using the same function:
![image](https://github.com/Tschipp/CarryOn/assets/50468096/b9352f94-7a9c-472d-b871-7a038c69dc77)
![image](https://github.com/Tschipp/CarryOn/assets/50468096/b45216c6-9c52-4764-886e-0bdb546005e3)


The right way it's something like that:
![image](https://github.com/Tschipp/CarryOn/assets/50468096/eccd1a87-ad2a-4fd6-9b6f-273edee09071)


I was trying to solve without the "/carryon place" or "/kill" and I was able to place mobs on another mobs head.

**Comment by Kaiwawa** [comment] 2023-11-07 19:52
I tried: 
Forge 47.1.3
-> CarryOn 2.1.2.5 and Rats 8.1.2 == Unable to drop
-> CarryOn 2.1.2.5 and Rats 8.0.5 == Able to drop

Forge 47.2.4
-> CarryOn 2.1.0.1 and Rats 8.1.2 == Unable to drop
-> CarryOn 2.1.0.1 and Rats 8.0.5 == Able to drop

Possible Fix: downgrade Carryon to use the last forge version and downgrade rats to be able to use Carryon 😂

**Comment by GizmoTheMoonPig** [comment] 2023-11-09 02:55
Hello, rats dev here. I've tracked down this issue and it will be fixed in 8.1.3 when I'm able to get it released. 
The problem here is that Carry On passes null as the difficulty when firing the FinalizeSpawn event. This field is never supposed to be null, and everything fails because I hook into this event and check the difficulty before anything else. I will be adding a bandaid fix but Carry On needs to pass the actual difficulty into the event.

**Comment by Tschipp** [comment] 2023-11-19 20:50
Will fix on my side too

**Closed as completed** 2024-02-28 08:36 UTC
Labels: bug, fixed in next release, 1.19
